/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Регистрация нового пользователя */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Вход пользователя */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Выход пользователя */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить информацию о текущем пользователе */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            /** Format: int64 */
            id: number;
            name: string;
            /** Format: email */
            email: string;
            /** Format: date-time */
            email_verified_at: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example Иван Иванов */
                    name: string;
                    /**
                     * Format: email
                     * @example ivan@example.com
                     */
                    email: string;
                    /**
                     * Format: password
                     * @example secret123
                     */
                    password: string;
                    /**
                     * Format: password
                     * @example secret123
                     */
                    password_confirmation?: string;
                };
            };
        };
        responses: {
            /** @description Пользователь зарегистрирован */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        /** @example Пользователь зарегистрирован */
                        message: string;
                        user: components["schemas"]["User"];
                        /** @example 1|abc123... */
                        token: string;
                    };
                };
            };
            /** @description Ошибка валидации */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success?: boolean;
                        /**
                         * @example {
                         *       "email": [
                         *         "The email has already been taken."
                         *       ],
                         *       "password": [
                         *         "The password must be at least 6 characters."
                         *       ]
                         *     }
                         */
                        errors?: Record<string, never>;
                    };
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: email
                     * @example ivan@example.com
                     */
                    email: string;
                    /**
                     * Format: password
                     * @example secret123
                     */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Успешный вход */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        /** @example Успешный вход */
                        message: string;
                        user: components["schemas"]["User"];
                        /** @example 1|abc123... */
                        token: string;
                    };
                };
            };
            /** @description Неверный email или пароль */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /**
                         * @example {
                         *       "email": [
                         *         "The email has already been taken."
                         *       ],
                         *       "password": [
                         *         "The password must be at least 6 characters."
                         *       ]
                         *     }
                         */
                        errors?: Record<string, never>;
                    };
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный выход */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success?: boolean;
                        /** @example Успешный выход */
                        message?: string;
                    };
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Информация о пользователе */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        user: components["schemas"]["User"];
                    };
                };
            };
        };
    };
}
